### ISSUE TITLE
Next complete starter gives Error: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by SaalkD** [preprio/next-complete-starter#3]
![Uploading Screenshot 2023-11-14 at 16.52.40.png…]()
After installing dependences, adding the acces token and hit run dev, only home and blog are working. The other pages give undefined reading error. 

I'm running node/react 18.2.0 and Next.js 14.0.2

**Comment by SaalkD** [comment]
Hi Kevin, thanks for your reply. I use the same steps as you did. Also using the key provided in the project. Home works fine. The other pages don't . See provided screenshot. 
<img width="1709" alt="Screenshot 2023-12-07 at 18 00 36" src="https://github.com/preprio/next-complete-starter/assets/150830475/e7b97359-78fd-4754-b43f-ac781c3ad17c">

**Comment by Kevintjuhz** [comment]
Hi Saalk,

When I download the project and use key: 7f05e9e2f17f1b3d5e08dab3a565acbea8b87745473917e159f70ae1cf0334b9 (the default key), run npm i & npm run dev, all the pages load fine.

See screenshot:
![image](https://github.com/preprio/next-complete-starter/assets/26409850/edda74ae-93ee-455e-bf95-72913069e3c2)

What is the JSON response when you console log the data object in the navigation Page?

**Comment by SaalkD** [comment]
Hi Kevin, 

Apparently, updating node.js to the latest version did the trick.

**Comment by Kevintjuhz** [comment]
Hi SaalkD, great you were able to resolve it. What was the node version you tried to use and didn't work?
